name: ChatEx-Refresh
main: de.jeter.chatex.ChatEx
version: 4.0.0
license: GPL-2.0
authors: [Jeter, Wizard_x, MrSpectrumYT]
description: ChatEx-Refresh — a fork of the ChatEx plugin for Folia, Leaf, Paper, Pufferfish and Purpur compatible with 1.21+
softdepend: [LuckPerms,Vault,PlaceholderAPI,Essentials]
api-version: 1.21
folia-supported: true

commands:
  chatex:
    description: The main command of the plugin
    aliases: [chat]
permissions:
  chatex.allowchat:
    description: Permission to use chat
    default: true
  chatex.chat.global:
    description: Permission to use global chat if ranged mode enabled
    default: op
  chatex.chat.colorlegacy:
    description: Permission to use legacy colors
    default: op
  chatex.chat.colorhex:
    description: Permission to use HEX colors
    default: op
  chatex.chat.magic:
    description: Permission to use magic color
    default: op
  chatex.antispam.bypass:
    description: Permission to bypass the antispam system
    default: op
  chatex.bypassads:
    description: Permission to bypass the AdBlocker
    default: op
  chatex.notifyad:
    description: Permission to be messaged when a player tries to advertise
    default: op
  chatex.notifyupdate:
    description: Permission to get notiefied about new updates when you join
    default: op
  chatex.clear:
    description: Permission to use /chatex clear to clear the chat
    default: op
  chatex.reload:
    description: Permission to use /chatex reload to reload the config and messages of ChatEx
    default: op
